DynamicLink: DynamicLink::FunctionWrapper< FuncType > Class Template Reference
DynamicLink::FunctionWrapper< FuncType > Class Template Reference
Core class contains safe dynamic function call.
#include <DynamicLink.h>
Public Types
using FuncPointer = std::add_pointer_t<FuncType>
using FuncPointer = std::add_pointer_t<FuncType>
Public Member Functions
FunctionWrapper (const std::string &libName, const std::string &funcName) noexcept
FunctionWrapper (FunctionWrapper &&)=default
FunctionWrapper & operator= (FunctionWrapper &&)=default
template<typename... Args>
auto operator() (Args... args) -> std::invoke_result_t< FuncType *, Args... >
main function to dynamic calls
template<typename T>
void setFallback (T &&func)
set the fallback function when the dynamic function accidentally failed
void setCheck (bool isCheck)
set the check state for the performance enable checking for the normal but safe performance disable checking for the high but unsafe performance
FuncPointer getRawPointer ()
for the best performance get the raw for calling
FunctionWrapper (const std::string &libName, const std::string &funcName) noexcept
FunctionWrapper (FunctionWrapper &&)=default
FunctionWrapper & operator= (FunctionWrapper &&)=default
template<typename... Args>
auto operator() (Args... args) -> std::invoke_result_t< FuncType *, Args... >
template<typename T>
void setFallback (T &&func)
void setCheck (bool isCheck)
FuncPointer getRawPointer ()
Private Attributes
Detail::FunctionDescriptor * descriptor {nullptr}
std::string libName
std::string funcName
std::unique_ptr< std::function< FuncType > > fallback
bool check {true}
Detailed Description
template<Callable FuncType>
class DynamicLink::FunctionWrapper< FuncType >
Core class contains safe dynamic function call.
Template Parameters
FuncType the dynamic function's real type
Warning
illegal FuncType will cause fatal at the function calling
Definition at line 30 of file DynamicLink.h.
Member Typedef Documentation
FuncPointer [1/2]
template<Callable FuncType> using DynamicLink::FunctionWrapper< FuncType >::FuncPointer = std::add_pointer_t<FuncType>
Definition at line 32 of file DynamicLink.h.
FuncPointer [2/2]
template<Callable FuncType> using DynamicLink::FunctionWrapper< FuncType >::FuncPointer = std::add_pointer_t<FuncType>
Definition at line 23 of file DynamicLink.ipp.
Constructor & Destructor Documentation
FunctionWrapper() [1/4]
template<Callable FuncType> DynamicLink::FunctionWrapper< FuncType >::FunctionWrapper (const std::string & libName, const std::string & funcName) explicit noexcept
References funcName, and libName.
Referenced by FunctionWrapper(), and operator=().
FunctionWrapper() [2/4]
template<Callable FuncType> DynamicLink::FunctionWrapper< FuncType >::FunctionWrapper (FunctionWrapper< FuncType > &&) default
References FunctionWrapper().
FunctionWrapper() [3/4]
template<Callable FuncType> DynamicLink::FunctionWrapper< FuncType >::FunctionWrapper (const std::string & libName, const std::string & funcName) inline explicit noexcept
Definition at line 24 of file DynamicLink.ipp.
References descriptor, funcName, Detail::GetFunctionImpl(), and libName.
FunctionWrapper() [4/4]
template<Callable FuncType> DynamicLink::FunctionWrapper< FuncType >::FunctionWrapper (FunctionWrapper< FuncType > &&) default
References FunctionWrapper().
Member Function Documentation
getRawPointer() [1/2]
template<Callable FuncType> FuncPointer DynamicLink::FunctionWrapper< FuncType >::getRawPointer ()
for the best performance get the raw for calling
Returns
the raw pointer of the dynamic function
Note
the pointer will cause error after unload/reload library, return null when fail to load function
getRawPointer() [2/2]
template<Callable FuncType> FuncPointer DynamicLink::FunctionWrapper< FuncType >::getRawPointer () inline
Definition at line 112 of file DynamicLink.ipp.
References descriptor.
operator()() [1/2]
template<Callable FuncType> template<typename... Args> auto DynamicLink::FunctionWrapper< FuncType >::operator() (Args... args) ->std::invoke_result_t< FuncType *, Args... >
main function to dynamic calls
Parameters
args the legal arguments the dynamic need, defined by the template FuncType
Returns
defined by the template FuncType
operator()() [2/2]
template<Callable FuncType> template<typename... Args> auto DynamicLink::FunctionWrapper< FuncType >::operator() (Args... args) ->std::invoke_result_t< FuncType *, Args... > inline
Definition at line 39 of file DynamicLink.ipp.
References check, descriptor, Detail::DescriptorShouldUpdate(), fallback, funcName, Detail::GetActualLibraryName(), Detail::GetFunctionImpl(), and libName.
operator=() [1/2]
template<Callable FuncType> FunctionWrapper & DynamicLink::FunctionWrapper< FuncType >::operator= (FunctionWrapper< FuncType > &&) default
References FunctionWrapper().
operator=() [2/2]
template<Callable FuncType> FunctionWrapper & DynamicLink::FunctionWrapper< FuncType >::operator= (FunctionWrapper< FuncType > &&) default
References FunctionWrapper().
setCheck() [1/2]
template<Callable FuncType> void DynamicLink::FunctionWrapper< FuncType >::setCheck (bool isCheck)
set the check state for the performance enable checking for the normal but safe performance disable checking for the high but unsafe performance
Parameters
isCheck true for enable checking, false for disable
Warning
when disable checking you should be responsible for the correct state
setCheck() [2/2]
template<Callable FuncType> void DynamicLink::FunctionWrapper< FuncType >::setCheck (bool isCheck) inline
Definition at line 108 of file DynamicLink.ipp.
References check.
setFallback() [1/2]
template<Callable FuncType> template<typename T> void DynamicLink::FunctionWrapper< FuncType >::setFallback (T && func)
set the fallback function when the dynamic function accidentally failed
Template Parameters
T any callables
Parameters
func when can't call the dynamic function will call this function as fallback
setFallback() [2/2]
template<Callable FuncType> template<typename T> void DynamicLink::FunctionWrapper< FuncType >::setFallback (T && func) inline
Definition at line 104 of file DynamicLink.ipp.
References fallback.
Member Data Documentation
check
template<Callable FuncType> bool DynamicLink::FunctionWrapper< FuncType >::check {true} private
Definition at line 122 of file DynamicLink.ipp.
Referenced by operator()(), and setCheck().
descriptor
template<Callable FuncType> Detail::FunctionDescriptor* DynamicLink::FunctionWrapper< FuncType >::descriptor {nullptr} private
Definition at line 117 of file DynamicLink.ipp.
Referenced by FunctionWrapper(), getRawPointer(), and operator()().
fallback
template<Callable FuncType> std::unique_ptr<std::function<FuncType> > DynamicLink::FunctionWrapper< FuncType >::fallback private
Definition at line 120 of file DynamicLink.ipp.
Referenced by operator()(), and setFallback().
funcName
template<Callable FuncType> std::string DynamicLink::FunctionWrapper< FuncType >::funcName private
Definition at line 119 of file DynamicLink.ipp.
Referenced by FunctionWrapper(), and operator()().
libName
template<Callable FuncType> std::string DynamicLink::FunctionWrapper< FuncType >::libName private
Definition at line 118 of file DynamicLink.ipp.
Referenced by FunctionWrapper(), and operator()().
The documentation for this class was generated from the following files:
include/DynamicLink.h
include/DynamicLink.ipp