DynamicLink: Detail Namespace Reference
Detail Namespace Reference
Classes
class CacheManager
struct FunctionDescriptor
Typedefs
using path = std::filesystem::path
Functions
FunctionDescriptor * GetFunctionImpl (const std::string &lib, const std::string &func)
bool DescriptorShouldUpdate (const std::string &libName)
std::string GetActualLibraryName (const std::string &oldLib)
LHANDLE LoadLibraryWithCheck (const std::string &lib)
bool IsFullName (std::string_view name)
std::string GetFullName (const std::string &)
void AddSearchPath (const std::string &)
std::optional< path > GetLibraryPath (const std::string &name)
bool IsValidPath (const std::string &name)
Typedef Documentation
path
using Detail::path = std::filesystem::path
Definition at line 14 of file LibraryFile.h.
Function Documentation
AddSearchPath()
void Detail::AddSearchPath (const std::string &)
DescriptorShouldUpdate()
bool Detail::DescriptorShouldUpdate (const std::string & libName)
References DescriptorShouldUpdate().
Referenced by DescriptorShouldUpdate(), and DynamicLink::FunctionWrapper< FuncType >::operator()().
GetActualLibraryName()
std::string Detail::GetActualLibraryName (const std::string & oldLib)
References GetActualLibraryName().
Referenced by GetActualLibraryName(), and DynamicLink::FunctionWrapper< FuncType >::operator()().
GetFullName()
std::string Detail::GetFullName (const std::string &)
GetFunctionImpl()
FunctionDescriptor * Detail::GetFunctionImpl (const std::string & lib, const std::string & func)
References GetFunctionImpl().
Referenced by DynamicLink::FunctionWrapper< FuncType >::FunctionWrapper(), GetFunctionImpl(), and DynamicLink::FunctionWrapper< FuncType >::operator()().
GetLibraryPath()
std::optional< path > Detail::GetLibraryPath (const std::string & name)
IsFullName()
bool Detail::IsFullName (std::string_view name)
IsValidPath()
bool Detail::IsValidPath (const std::string & name)
LoadLibraryWithCheck()
LHANDLE Detail::LoadLibraryWithCheck (const std::string & lib)
References LoadLibraryWithCheck().
Referenced by LoadLibraryWithCheck().