DynamicLink: Detail::FunctionDescriptor Struct Reference
Detail::FunctionDescriptor Struct Reference
#include <DynamicLinkImpl.h>
Public Member Functions
FunctionDescriptor ()
FunctionDescriptor (uintptr_t)
FunctionDescriptor (const FunctionDescriptor &) noexcept
FunctionDescriptor & operator= (FunctionDescriptor &&) noexcept
FunctionDescriptor & operator= (const FunctionDescriptor &) noexcept
FunctionDescriptor & operator= (uintptr_t)
Public Attributes
uintptr_t functionPointer
std::shared_mutex valid
Detailed Description
Definition at line 11 of file DynamicLinkImpl.h.
Constructor & Destructor Documentation
FunctionDescriptor() [1/3]
Detail::FunctionDescriptor::FunctionDescriptor ()
Referenced by FunctionDescriptor(), operator=(), operator=(), and operator=().
FunctionDescriptor() [2/3]
Detail::FunctionDescriptor::FunctionDescriptor (uintptr_t) explicit
FunctionDescriptor() [3/3]
Detail::FunctionDescriptor::FunctionDescriptor (const FunctionDescriptor &) noexcept
References FunctionDescriptor().
Member Function Documentation
operator=() [1/3]
FunctionDescriptor & Detail::FunctionDescriptor::operator= (const FunctionDescriptor &) noexcept
References FunctionDescriptor().
operator=() [2/3]
FunctionDescriptor & Detail::FunctionDescriptor::operator= (FunctionDescriptor &&) noexcept
References FunctionDescriptor().
operator=() [3/3]
FunctionDescriptor & Detail::FunctionDescriptor::operator= (uintptr_t)
References FunctionDescriptor().
Member Data Documentation
functionPointer
uintptr_t Detail::FunctionDescriptor::functionPointer
Definition at line 19 of file DynamicLinkImpl.h.
valid
std::shared_mutex Detail::FunctionDescriptor::valid
Definition at line 20 of file DynamicLinkImpl.h.
The documentation for this struct was generated from the following file:
include/internal/DynamicLinkImpl.h